amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2  # 里程计旋转噪声
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    base_frame_id: "base_link"
    odom_frame_id: "odom"

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      min_vel_x: 0.0
      max_vel_x: 0.3
      max_vel_y: 0.0
      max_vel_theta: 1.0
      acc_lim_x: 0.5
      acc_lim_theta: 1.5
      decel_lim_x: 0.5
      decel_lim_theta: 1.5
      sim_time: 1.5
      vx_samples: 20
      vy_samples: 5
      vtheta_samples: 20
      path_distance_bias: 32.0
      goal_distance_bias: 24.0
      occdist_scale: 0.2
      inflation_radius: 0.18  # 关键：比车宽略大

bt_navigator:
  ros__parameters:
    use_sim_time: False
    default_nav_to_pose_bt_xml: ""
    default_follow_waypoints_bt_xml: ""